/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "kdjpodkanmozdarlyavh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtkanBvZGthbm1vemRhcmx5YXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTA3MDksImV4cCI6MjA4ODcyNjcwOX0.9rhqY37-cu3-SyhlBl3g2qaLebMLcGHSmBa_C_tj24I"