import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'kn' | 'ta' | 'te' | 'ml' | 'bn' | 'gu' | 'mr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    appName: 'Namma Suraksha',
    slogan: 'Be a Proud Citizen',
    loginAsCitizen: 'Login as Citizen',
    loginAsAuthority: 'Login as Authority',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    signup: 'Sign Up',
    dashboard: 'Dashboard',
    reportAccident: 'Report Accident',
    reportViolation: 'Report Violation',
    myRewards: 'My Rewards',
    profile: 'Profile',
    logout: 'Logout',
    streaks: 'Streaks',
    points: 'Points',
    totalComplaints: 'Total Complaints',
    pendingApproval: 'Pending Approval',
    approved: 'Approved',
    sosEmergency: 'SOS Emergency',
    callAmbulance: 'Call Ambulance',
    callPolice: 'Call Police',
    nearbyHospital: 'Find Nearby Hospital',
    emergencyContacted: 'Emergency services contacted!',
    trafficViolation: 'Traffic Violation',
    uploadPhoto: 'Upload Photo',
    recordVoice: 'Record Voice Description',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    submitComplaint: 'Submit Complaint',
    complaintSubmitted: 'Complaint submitted successfully!',
    congratulations: 'Congratulations!',
    newStreakUnlocked: 'You unlocked a new streak!',
    rewardEarned: 'Reward Earned!',
    shareOnSocial: 'Share on Social Media',
    responsibleCitizen: 'Responsible Citizen',
    violationTypes: 'Types of Violations You Can Report',
    wrongParking: 'Wrong Parking',
    noHelmet: 'Not Wearing Helmet',
    signalJump: 'Signal Jumping',
    overSpeeding: 'Over Speeding',
    wrongSide: 'Driving on Wrong Side',
    damagedRoad: 'Damaged Road',
    otherViolation: 'Other Violation',
    highAccidentZones: 'High Accident Zones',
    selectLanguage: 'Select Language',
    upiId: 'UPI ID',
    connectUpi: 'Connect UPI for Rewards',
    scratchCard: 'Scratch Card Reward',
    discountCoupon: 'Discount Coupon',
    pendingComplaints: 'Pending Complaints for Approval',
    approveComplaint: 'Approve',
    rejectComplaint: 'Reject',
    numberPlate: 'Number Plate',
    voiceDescription: 'Voice Description',
    exampleComplaints: 'Example Complaints',
    viewExamples: 'View Examples',
    yourAvatar: 'Your Avatar',
    editProfile: 'Edit Profile',
    name: 'Name',
    phoneNumber: 'Phone Number',
    save: 'Save',
    rewardsHistory: 'Rewards History',
    cashReward: 'Cash Reward',
    pointsRequired: 'Points Required',
    claimReward: 'Claim Reward',
    reportDescription: 'Description',
    location: 'Location',
  },
  hi: {
    appName: 'नम्मा सुरक्षा',
    slogan: 'एक गर्वित नागरिक बनें',
    loginAsCitizen: 'नागरिक के रूप में लॉगिन',
    loginAsAuthority: 'अधिकारी के रूप में लॉगिन',
    email: 'ईमेल',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    signup: 'साइन अप',
    dashboard: 'डैशबोर्ड',
    reportAccident: 'दुर्घटना की रिपोर्ट',
    reportViolation: 'उल्लंघन की रिपोर्ट',
    myRewards: 'मेरे पुरस्कार',
    profile: 'प्रोफ़ाइल',
    logout: 'लॉगआउट',
    streaks: 'स्ट्रीक्स',
    points: 'अंक',
    totalComplaints: 'कुल शिकायतें',
    pendingApproval: 'स्वीकृति लंबित',
    approved: 'स्वीकृत',
    sosEmergency: 'एसओएस आपातकाल',
    callAmbulance: 'एम्बुलेंस बुलाएं',
    callPolice: 'पुलिस बुलाएं',
    nearbyHospital: 'नजदीकी अस्पताल खोजें',
    emergencyContacted: 'आपातकालीन सेवाओं से संपर्क किया!',
    trafficViolation: 'यातायात उल्लंघन',
    uploadPhoto: 'फोटो अपलोड करें',
    recordVoice: 'आवाज विवरण रिकॉर्ड करें',
    startRecording: 'रिकॉर्डिंग शुरू करें',
    stopRecording: 'रिकॉर्डिंग बंद करें',
    submitComplaint: 'शिकायत सबमिट करें',
    complaintSubmitted: 'शिकायत सफलतापूर्वक सबमिट की गई!',
    congratulations: 'बधाई हो!',
    newStreakUnlocked: 'आपने एक नया स्ट्रीक अनलॉक किया!',
    rewardEarned: 'पुरस्कार अर्जित!',
    shareOnSocial: 'सोशल मीडिया पर साझा करें',
    responsibleCitizen: 'जिम्मेदार नागरिक',
    violationTypes: 'उल्लंघन के प्रकार जो आप रिपोर्ट कर सकते हैं',
    wrongParking: 'गलत पार्किंग',
    noHelmet: 'हेलमेट नहीं पहना',
    signalJump: 'सिग्नल तोड़ना',
    overSpeeding: 'अधिक गति',
    wrongSide: 'गलत साइड पर चलना',
    damagedRoad: 'क्षतिग्रस्त सड़क',
    otherViolation: 'अन्य उल्लंघन',
    highAccidentZones: 'उच्च दुर्घटना क्षेत्र',
    selectLanguage: 'भाषा चुनें',
    upiId: 'यूपीआई आईडी',
    connectUpi: 'पुरस्कारों के लिए यूपीआई कनेक्ट करें',
    scratchCard: 'स्क्रैच कार्ड पुरस्कार',
    discountCoupon: 'छूट कूपन',
    pendingComplaints: 'स्वीकृति के लिए लंबित शिकायतें',
    approveComplaint: 'स्वीकृत करें',
    rejectComplaint: 'अस्वीकार करें',
    numberPlate: 'नंबर प्लेट',
    voiceDescription: 'आवाज विवरण',
    exampleComplaints: 'उदाहरण शिकायतें',
    viewExamples: 'उदाहरण देखें',
    yourAvatar: 'आपका अवतार',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    name: 'नाम',
    phoneNumber: 'फोन नंबर',
    save: 'सहेजें',
    rewardsHistory: 'पुरस्कार इतिहास',
    cashReward: 'नकद पुरस्कार',
    pointsRequired: 'आवश्यक अंक',
    claimReward: 'पुरस्कार प्राप्त करें',
    reportDescription: 'विवरण',
    location: 'स्थान',
  },
  kn: {
    appName: 'ನಮ್ಮ ಸುರಕ್ಷಾ',
    slogan: 'ಹೆಮ್ಮೆಯ ನಾಗರಿಕರಾಗಿ',
    loginAsCitizen: 'ನಾಗರಿಕರಾಗಿ ಲಾಗಿನ್',
    loginAsAuthority: 'ಅಧಿಕಾರಿಯಾಗಿ ಲಾಗಿನ್',
    email: 'ಇಮೇಲ್',
    password: 'ಪಾಸ್‌ವರ್ಡ್',
    login: 'ಲಾಗಿನ್',
    signup: 'ಸೈನ್ ಅಪ್',
    dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    reportAccident: 'ಅಪಘಾತ ವರದಿ',
    reportViolation: 'ಉಲ್ಲಂಘನೆ ವರದಿ',
    myRewards: 'ನನ್ನ ಬಹುಮಾನಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',
    logout: 'ಲಾಗ್ಔಟ್',
    streaks: 'ಸ್ಟ್ರೀಕ್ಸ್',
    points: 'ಅಂಕಗಳು',
    totalComplaints: 'ಒಟ್ಟು ದೂರುಗಳು',
    pendingApproval: 'ಅನುಮೋದನೆ ಬಾಕಿ',
    approved: 'ಅನುಮೋದಿತ',
    sosEmergency: 'SOS ತುರ್ತು',
    callAmbulance: 'ಆಂಬುಲೆನ್ಸ್ ಕರೆ',
    callPolice: 'ಪೊಲೀಸ್ ಕರೆ',
    nearbyHospital: 'ಹತ್ತಿರದ ಆಸ್ಪತ್ರೆ ಹುಡುಕಿ',
    emergencyContacted: 'ತುರ್ತು ಸೇವೆಗಳನ್ನು ಸಂಪರ್ಕಿಸಲಾಗಿದೆ!',
    trafficViolation: 'ಟ್ರಾಫಿಕ್ ಉಲ್ಲಂಘನೆ',
    uploadPhoto: 'ಫೋಟೋ ಅಪ್ಲೋಡ್',
    recordVoice: 'ಧ್ವನಿ ವಿವರಣೆ ರೆಕಾರ್ಡ್',
    startRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ಪ್ರಾರಂಭ',
    stopRecording: 'ರೆಕಾರ್ಡಿಂಗ್ ನಿಲ್ಲಿಸಿ',
    submitComplaint: 'ದೂರು ಸಲ್ಲಿಸಿ',
    complaintSubmitted: 'ದೂರು ಯಶಸ್ವಿಯಾಗಿ ಸಲ್ಲಿಸಲಾಗಿದೆ!',
    congratulations: 'ಅಭಿನಂದನೆಗಳು!',
    newStreakUnlocked: 'ನೀವು ಹೊಸ ಸ್ಟ್ರೀಕ್ ಅನ್ಲಾಕ್ ಮಾಡಿದ್ದೀರಿ!',
    rewardEarned: 'ಬಹುಮಾನ ಗಳಿಸಿದೆ!',
    shareOnSocial: 'ಸಾಮಾಜಿಕ ಮಾಧ್ಯಮದಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
    responsibleCitizen: 'ಜವಾಬ್ದಾರಿಯುತ ನಾಗರಿಕ',
    violationTypes: 'ನೀವು ವರದಿ ಮಾಡಬಹುದಾದ ಉಲ್ಲಂಘನೆಗಳ ವಿಧಗಳು',
    wrongParking: 'ತಪ್ಪು ಪಾರ್ಕಿಂಗ್',
    noHelmet: 'ಹೆಲ್ಮೆಟ್ ಧರಿಸದಿರುವುದು',
    signalJump: 'ಸಿಗ್ನಲ್ ಜಂಪಿಂಗ್',
    overSpeeding: 'ಅತಿಯಾದ ವೇಗ',
    wrongSide: 'ತಪ್ಪು ಬದಿಯಲ್ಲಿ ಚಾಲನೆ',
    damagedRoad: 'ಹಾನಿಗೊಳಗಾದ ರಸ್ತೆ',
    otherViolation: 'ಇತರ ಉಲ್ಲಂಘನೆ',
    highAccidentZones: 'ಹೆಚ್ಚಿನ ಅಪಘಾತ ವಲಯಗಳು',
    selectLanguage: 'ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ',
    upiId: 'UPI ID',
    connectUpi: 'ಬಹುಮಾನಗಳಿಗಾಗಿ UPI ಸಂಪರ್ಕಿಸಿ',
    scratchCard: 'ಸ್ಕ್ರಾಚ್ ಕಾರ್ಡ್ ಬಹುಮಾನ',
    discountCoupon: 'ರಿಯಾಯಿತಿ ಕೂಪನ್',
    pendingComplaints: 'ಅನುಮೋದನೆಗಾಗಿ ಬಾಕಿ ದೂರುಗಳು',
    approveComplaint: 'ಅನುಮೋದಿಸಿ',
    rejectComplaint: 'ತಿರಸ್ಕರಿಸಿ',
    numberPlate: 'ಸಂಖ್ಯೆ ಫಲಕ',
    voiceDescription: 'ಧ್ವನಿ ವಿವರಣೆ',
    exampleComplaints: 'ಉದಾಹರಣೆ ದೂರುಗಳು',
    viewExamples: 'ಉದಾಹರಣೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
    yourAvatar: 'ನಿಮ್ಮ ಅವತಾರ',
    editProfile: 'ಪ್ರೊಫೈಲ್ ಸಂಪಾದಿಸಿ',
    name: 'ಹೆಸರು',
    phoneNumber: 'ಫೋನ್ ಸಂಖ್ಯೆ',
    save: 'ಉಳಿಸಿ',
    rewardsHistory: 'ಬಹುಮಾನಗಳ ಇತಿಹಾಸ',
    cashReward: 'ನಗದು ಬಹುಮಾನ',
    pointsRequired: 'ಅಗತ್ಯವಿರುವ ಅಂಕಗಳು',
    claimReward: 'ಬಹುಮಾನ ಪಡೆಯಿರಿ',
    reportDescription: 'ವಿವರಣೆ',
    location: 'ಸ್ಥಳ',
  },
  ta: {
    appName: 'நம்ம சுரக்ஷா',
    slogan: 'பெருமைமிக்க குடிமகனாக இருங்கள்',
    loginAsCitizen: 'குடிமகனாக உள்நுழைய',
    loginAsAuthority: 'அதிகாரியாக உள்நுழைய',
    email: 'மின்னஞ்சல்',
    password: 'கடவுச்சொல்',
    login: 'உள்நுழைய',
    signup: 'பதிவு செய்ய',
    dashboard: 'டாஷ்போர்டு',
    reportAccident: 'விபத்து அறிக்கை',
    reportViolation: 'மீறல் அறிக்கை',
    myRewards: 'எனது வெகுமதிகள்',
    profile: 'சுயவிவரம்',
    logout: 'வெளியேறு',
    streaks: 'ஸ்ட்ரீக்ஸ்',
    points: 'புள்ளிகள்',
    totalComplaints: 'மொத்த புகார்கள்',
    pendingApproval: 'ஒப்புதல் நிலுவையில்',
    approved: 'அங்கீகரிக்கப்பட்டது',
    sosEmergency: 'SOS அவசரம்',
    callAmbulance: 'ஆம்புலன்ஸை அழை',
    callPolice: 'காவல்துறையை அழை',
    nearbyHospital: 'அருகிலுள்ள மருத்துவமனையைக் கண்டறி',
    emergencyContacted: 'அவசர சேவைகள் தொடர்பு கொள்ளப்பட்டன!',
    trafficViolation: 'போக்குவரத்து மீறல்',
    uploadPhoto: 'புகைப்படம் பதிவேற்று',
    recordVoice: 'குரல் விவரத்தை பதிவு செய்',
    startRecording: 'பதிவு தொடங்கு',
    stopRecording: 'பதிவு நிறுத்து',
    submitComplaint: 'புகார் சமர்ப்பி',
    complaintSubmitted: 'புகார் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது!',
    congratulations: 'வாழ்த்துகள்!',
    newStreakUnlocked: 'நீங்கள் புதிய ஸ்ட்ரீக்கை திறந்துள்ளீர்கள்!',
    rewardEarned: 'வெகுமதி பெற்றீர்கள்!',
    shareOnSocial: 'சமூக ஊடகங்களில் பகிர்',
    responsibleCitizen: 'பொறுப்பான குடிமகன்',
    violationTypes: 'நீங்கள் அறிக்கை செய்யக்கூடிய மீறல்களின் வகைகள்',
    wrongParking: 'தவறான பார்க்கிங்',
    noHelmet: 'ஹெல்மெட் அணியாதது',
    signalJump: 'சிக்னல் ஜம்பிங்',
    overSpeeding: 'அதிக வேகம்',
    wrongSide: 'தவறான பக்கத்தில் ஓட்டுதல்',
    damagedRoad: 'சேதமடைந்த சாலை',
    otherViolation: 'பிற மீறல்',
    highAccidentZones: 'உயர் விபத்து பகுதிகள்',
    selectLanguage: 'மொழியைத் தேர்ந்தெடு',
    upiId: 'UPI ID',
    connectUpi: 'வெகுமதிகளுக்கு UPI இணை',
    scratchCard: 'ஸ்க்ராட்ச் கார்டு வெகுமதி',
    discountCoupon: 'தள்ளுபடி கூப்பன்',
    pendingComplaints: 'ஒப்புதலுக்கு நிலுவையில் உள்ள புகார்கள்',
    approveComplaint: 'அங்கீகரி',
    rejectComplaint: 'நிராகரி',
    numberPlate: 'எண் தகடு',
    voiceDescription: 'குரல் விவரம்',
    exampleComplaints: 'உதாரண புகார்கள்',
    viewExamples: 'உதாரணங்களைக் காண்க',
    yourAvatar: 'உங்கள் அவதாரம்',
    editProfile: 'சுயவிவரத்தைத் திருத்து',
    name: 'பெயர்',
    phoneNumber: 'தொலைபேசி எண்',
    save: 'சேமி',
    rewardsHistory: 'வெகுமதி வரலாறு',
    cashReward: 'பண வெகுமதி',
    pointsRequired: 'தேவையான புள்ளிகள்',
    claimReward: 'வெகுமதியைப் பெறு',
    reportDescription: 'விவரம்',
    location: 'இடம்',
  },
  te: {
    appName: 'నమ్మ సురక్ష',
    slogan: 'గర్వించదగిన పౌరుడు కండి',
    loginAsCitizen: 'పౌరుడిగా లాగిన్',
    loginAsAuthority: 'అధికారిగా లాగిన్',
    email: 'ఇమెయిల్',
    password: 'పాస్‌వర్డ్',
    login: 'లాగిన్',
    signup: 'సైన్ అప్',
    dashboard: 'డాష్‌బోర్డ్',
    reportAccident: 'ప్రమాద నివేదిక',
    reportViolation: 'ఉల్లంఘన నివేదిక',
    myRewards: 'నా బహుమతులు',
    profile: 'ప్రొఫైల్',
    logout: 'లాగౌట్',
    streaks: 'స్ట్రీక్స్',
    points: 'పాయింట్లు',
    totalComplaints: 'మొత్తం ఫిర్యాదులు',
    pendingApproval: 'ఆమోదం పెండింగ్',
    approved: 'ఆమోదించబడింది',
    sosEmergency: 'SOS అత్యవసరం',
    callAmbulance: 'అంబులెన్స్ కాల్',
    callPolice: 'పోలీసు కాల్',
    nearbyHospital: 'సమీప ఆసుపత్రి కనుగొనండి',
    emergencyContacted: 'అత్యవసర సేవలు సంప్రదించబడ్డాయి!',
    trafficViolation: 'ట్రాఫిక్ ఉల్లంఘన',
    uploadPhoto: 'ఫోటో అప్‌లోడ్',
    recordVoice: 'వాయిస్ వివరణను రికార్డ్ చేయండి',
    startRecording: 'రికార్డింగ్ ప్రారంభించు',
    stopRecording: 'రికార్డింగ్ ఆపు',
    submitComplaint: 'ఫిర్యాదు సమర్పించు',
    complaintSubmitted: 'ఫిర్యాదు విజయవంతంగా సమర్పించబడింది!',
    congratulations: 'అభినందనలు!',
    newStreakUnlocked: 'మీరు కొత్త స్ట్రీక్‌ను అన్‌లాక్ చేసారు!',
    rewardEarned: 'బహుమతి సంపాదించారు!',
    shareOnSocial: 'సోషల్ మీడియాలో షేర్ చేయండి',
    responsibleCitizen: 'బాధ్యతాయుత పౌరుడు',
    violationTypes: 'మీరు నివేదించగల ఉల్లంఘనల రకాలు',
    wrongParking: 'తప్పు పార్కింగ్',
    noHelmet: 'హెల్మెట్ ధరించడం లేదు',
    signalJump: 'సిగ్నల్ జంపింగ్',
    overSpeeding: 'అతి వేగం',
    wrongSide: 'తప్పు వైపు డ్రైవింగ్',
    damagedRoad: 'దెబ్బతిన్న రోడ్డు',
    otherViolation: 'ఇతర ఉల్లంఘన',
    highAccidentZones: 'అధిక ప్రమాద జోన్లు',
    selectLanguage: 'భాష ఎంచుకోండి',
    upiId: 'UPI ID',
    connectUpi: 'బహుమతుల కోసం UPI కనెక్ట్ చేయండి',
    scratchCard: 'స్క్రాచ్ కార్డ్ బహుమతి',
    discountCoupon: 'డిస్కౌంట్ కూపన్',
    pendingComplaints: 'ఆమోదం కోసం పెండింగ్ ఫిర్యాదులు',
    approveComplaint: 'ఆమోదించు',
    rejectComplaint: 'తిరస్కరించు',
    numberPlate: 'నంబర్ ప్లేట్',
    voiceDescription: 'వాయిస్ వివరణ',
    exampleComplaints: 'ఉదాహరణ ఫిర్యాదులు',
    viewExamples: 'ఉదాహరణలు వీక్షించండి',
    yourAvatar: 'మీ అవతార్',
    editProfile: 'ప్రొఫైల్ సవరించు',
    name: 'పేరు',
    phoneNumber: 'ఫోన్ నంబర్',
    save: 'సేవ్',
    rewardsHistory: 'బహుమతుల చరిత్ర',
    cashReward: 'నగదు బహుమతి',
    pointsRequired: 'అవసరమైన పాయింట్లు',
    claimReward: 'బహుమతిని క్లెయిమ్ చేయండి',
    reportDescription: 'వివరణ',
    location: 'స్థానం',
  },
  ml: {
    appName: 'നമ്മ സുരക്ഷാ',
    slogan: 'അഭിമാനമുള്ള പൗരനാകൂ',
    loginAsCitizen: 'പൗരനായി ലോഗിൻ',
    loginAsAuthority: 'അധികാരിയായി ലോഗിൻ',
    email: 'ഇമെയിൽ',
    password: 'പാസ്‌വേഡ്',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    reportAccident: 'അപകട റിപ്പോർട്ട്',
    reportViolation: 'ലംഘന റിപ്പോർട്ട്',
    myRewards: 'എന്റെ പുരസ്‌കാരങ്ങൾ',
    profile: 'പ്രൊഫൈൽ',
    logout: 'ലോഗൗട്ട്',
    streaks: 'സ്ട്രീക്സ്',
    points: 'പോയിന്റുകൾ',
    totalComplaints: 'ആകെ പരാതികൾ',
    pendingApproval: 'അംഗീകാരം ബാക്കി',
    approved: 'അംഗീകരിച്ചു',
    sosEmergency: 'SOS അടിയന്തരം',
    callAmbulance: 'ആംബുലൻസ് വിളിക്കൂ',
    callPolice: 'പോലീസിനെ വിളിക്കൂ',
    nearbyHospital: 'സമീപത്തുള്ള ആശുപത്രി കണ്ടെത്തൂ',
    emergencyContacted: 'അടിയന്തര സേവനങ്ങൾ ബന്ധപ്പെട്ടു!',
    trafficViolation: 'ട്രാഫിക് ലംഘനം',
    uploadPhoto: 'ഫോട്டോ അപ്‌ലോഡ് ചെയ്യൂ',
    recordVoice: 'ശബ്ദ വിവരണം റെക്കോർഡ് ചെയ്യൂ',
    startRecording: 'റെക്കോർഡിംഗ് ആരംഭിക്കൂ',
    stopRecording: 'റെക്കോർഡിംഗ് നിർത്തൂ',
    submitComplaint: 'പരാതി സമർപ്പിക്കൂ',
    complaintSubmitted: 'പരാതി വിജയകരമായി സമർപ്പിച്ചു!',
    congratulations: 'അഭിനന്ദനങ്ങൾ!',
    newStreakUnlocked: 'നിങ്ങൾ ഒരു പുതിയ സ്ട്രീക് അൺലോക്ക് ചെയ്തു!',
    rewardEarned: 'പുരസ്‌കാരം നേടി!',
    shareOnSocial: 'സോഷ്യൽ മീഡിയയിൽ പങ്കിടൂ',
    responsibleCitizen: 'ഉത്തരവാദിത്തമുള്ള പൗരൻ',
    violationTypes: 'നിങ്ങൾക്ക് റിപ്പോർട്ട് ചെയ്യാവുന്ന ലംഘനങ്ങളുടെ തരങ്ങൾ',
    wrongParking: 'തെറ്റായ പാർക്കിംഗ്',
    noHelmet: 'ഹെൽമെറ്റ് ധരിക്കാത്തത്',
    signalJump: 'സിഗ്നൽ ജമ്പിംഗ്',
    overSpeeding: 'അമിത വേഗത',
    wrongSide: 'തെറ്റായ വശത്ത് ഡ്രൈവിംഗ്',
    damagedRoad: 'കേടായ റോഡ്',
    otherViolation: 'മറ്റ് ലംഘനം',
    highAccidentZones: 'ഉയർന്ന അപകട മേഖലകൾ',
    selectLanguage: 'ഭാഷ തിരഞ്ഞെടുക്കൂ',
    upiId: 'UPI ID',
    connectUpi: 'പുരസ്‌കാരങ്ങൾക്കായി UPI കണക്റ്റ് ചെയ്യൂ',
    scratchCard: 'സ്ക്രാച്ച് കാർഡ് പുരസ്‌കാരം',
    discountCoupon: 'ഡിസ്കൗണ്ട് കൂപ്പൺ',
    pendingComplaints: 'അംഗീകാരത്തിനായി കാത്തിരിക്കുന്ന പരാതികൾ',
    approveComplaint: 'അംഗീകരിക്കൂ',
    rejectComplaint: 'നിരസിക്കൂ',
    numberPlate: 'നമ്പർ പ്ലേറ്റ്',
    voiceDescription: 'ശബ്ദ വിവരണം',
    exampleComplaints: 'ഉദാഹരണ പരാതികൾ',
    viewExamples: 'ഉദാഹരണങ്ങൾ കാണൂ',
    yourAvatar: 'നിങ്ങളുടെ അവതാർ',
    editProfile: 'പ്രൊഫൈൽ എഡിറ്റ് ചെയ്യൂ',
    name: 'പേര്',
    phoneNumber: 'ഫോൺ നമ്പർ',
    save: 'സേവ് ചെയ്യൂ',
    rewardsHistory: 'പുരസ്‌കാര ചരിത്രം',
    cashReward: 'കാഷ് പുരസ്‌കാരം',
    pointsRequired: 'ആവശ്യമായ പോയിന്റുകൾ',
    claimReward: 'പുരസ്‌കാരം ക്ലെയിം ചെയ്യൂ',
    reportDescription: 'വിവരണം',
    location: 'സ്ഥലം',
  },
  bn: {
    appName: 'নাম্মা সুরক্ষা',
    slogan: 'গর্বিত নাগরিক হন',
    loginAsCitizen: 'নাগরিক হিসেবে লগইন',
    loginAsAuthority: 'কর্তৃপক্ষ হিসেবে লগইন',
    email: 'ইমেল',
    password: 'পাসওয়ার্ড',
    login: 'লগইন',
    signup: 'সাইন আপ',
    dashboard: 'ড্যাশবোর্ড',
    reportAccident: 'দুর্ঘটনার রিপোর্ট',
    reportViolation: 'লঙ্ঘনের রিপোর্ট',
    myRewards: 'আমার পুরস্কার',
    profile: 'প্রোফাইল',
    logout: 'লগআউট',
    streaks: 'স্ট্রীক',
    points: 'পয়েন্ট',
    totalComplaints: 'মোট অভিযোগ',
    pendingApproval: 'অনুমোদন বাকি',
    approved: 'অনুমোদিত',
    sosEmergency: 'SOS জরুরি',
    callAmbulance: 'অ্যাম্বুলেন্স কল',
    callPolice: 'পুলিশ কল',
    nearbyHospital: 'কাছের হাসপাতাল খুঁজুন',
    emergencyContacted: 'জরুরি সেবা যোগাযোগ করা হয়েছে!',
    trafficViolation: 'ট্রাফিক লঙ্ঘন',
    uploadPhoto: 'ফটো আপলোড',
    recordVoice: 'ভয়েস বিবরণ রেকর্ড করুন',
    startRecording: 'রেকর্ডিং শুরু করুন',
    stopRecording: 'রেকর্ডিং বন্ধ করুন',
    submitComplaint: 'অভিযোগ জমা দিন',
    complaintSubmitted: 'অভিযোগ সফলভাবে জমা দেওয়া হয়েছে!',
    congratulations: 'অভিনন্দন!',
    newStreakUnlocked: 'আপনি একটি নতুন স্ট্রীক আনলক করেছেন!',
    rewardEarned: 'পুরস্কার অর্জন!',
    shareOnSocial: 'সোশ্যাল মিডিয়ায় শেয়ার করুন',
    responsibleCitizen: 'দায়িত্বশীল নাগরিক',
    violationTypes: 'আপনি যে ধরনের লঙ্ঘন রিপোর্ট করতে পারেন',
    wrongParking: 'ভুল পার্কিং',
    noHelmet: 'হেলমেট পরা নেই',
    signalJump: 'সিগন্যাল জাম্পিং',
    overSpeeding: 'অতিরিক্ত গতি',
    wrongSide: 'ভুল দিকে গাড়ি চালানো',
    damagedRoad: 'ক্ষতিগ্রস্ত রাস্তা',
    otherViolation: 'অন্যান্য লঙ্ঘন',
    highAccidentZones: 'উচ্চ দুর্ঘটনা এলাকা',
    selectLanguage: 'ভাষা নির্বাচন করুন',
    upiId: 'UPI ID',
    connectUpi: 'পুরস্কারের জন্য UPI সংযুক্ত করুন',
    scratchCard: 'স্ক্র্যাচ কার্ড পুরস্কার',
    discountCoupon: 'ছাড় কুপন',
    pendingComplaints: 'অনুমোদনের জন্য অপেক্ষমাণ অভিযোগ',
    approveComplaint: 'অনুমোদন করুন',
    rejectComplaint: 'প্রত্যাখ্যান করুন',
    numberPlate: 'নম্বর প্লেট',
    voiceDescription: 'ভয়েস বিবরণ',
    exampleComplaints: 'উদাহরণ অভিযোগ',
    viewExamples: 'উদাহরণ দেখুন',
    yourAvatar: 'আপনার অবতার',
    editProfile: 'প্রোফাইল সম্পাদনা',
    name: 'নাম',
    phoneNumber: 'ফোন নম্বর',
    save: 'সংরক্ষণ',
    rewardsHistory: 'পুরস্কার ইতিহাস',
    cashReward: 'নগদ পুরস্কার',
    pointsRequired: 'প্রয়োজনীয় পয়েন্ট',
    claimReward: 'পুরস্কার দাবি করুন',
    reportDescription: 'বিবরণ',
    location: 'অবস্থান',
  },
  gu: {
    appName: 'નમ્મા સુરક્ષા',
    slogan: 'ગૌરવપૂર્ણ નાગરિક બનો',
    loginAsCitizen: 'નાગરિક તરીકે લોગિન',
    loginAsAuthority: 'સત્તાવાળા તરીકે લોગિન',
    email: 'ઇમેઇલ',
    password: 'પાસવર્ડ',
    login: 'લોગિન',
    signup: 'સાઇન અપ',
    dashboard: 'ડેશબોર્ડ',
    reportAccident: 'અકસ્માત રિપોર્ટ',
    reportViolation: 'ઉલ્લંઘન રિપોર્ટ',
    myRewards: 'મારા પુરસ્કારો',
    profile: 'પ્રોફાઇલ',
    logout: 'લોગઆઉટ',
    streaks: 'સ્ટ્રીક્સ',
    points: 'પોઇન્ટ્સ',
    totalComplaints: 'કુલ ફરિયાદો',
    pendingApproval: 'મંજૂરી બાકી',
    approved: 'મંજૂર',
    sosEmergency: 'SOS કટોકટી',
    callAmbulance: 'એમ્બ્યુલન્સ કૉલ',
    callPolice: 'પોલીસ કૉલ',
    nearbyHospital: 'નજીકની હોસ્પિટલ શોધો',
    emergencyContacted: 'કટોકટી સેવાઓનો સંપર્ક કર્યો!',
    trafficViolation: 'ટ્રાફિક ઉલ્લંઘન',
    uploadPhoto: 'ફોટો અપલોડ',
    recordVoice: 'વૉઇસ વર્ણન રેકોર્ડ કરો',
    startRecording: 'રેકોર્ડિંગ શરૂ કરો',
    stopRecording: 'રેકોર્ડિંગ બંધ કરો',
    submitComplaint: 'ફરિયાદ સબમિટ કરો',
    complaintSubmitted: 'ફરિયાદ સફળતાપૂર્વક સબમિટ થઈ!',
    congratulations: 'અભિનંદન!',
    newStreakUnlocked: 'તમે નવી સ્ટ્રીક અનલૉક કરી!',
    rewardEarned: 'પુરસ્કાર મેળવ્યો!',
    shareOnSocial: 'સોશિયલ મીડિયા પર શેર કરો',
    responsibleCitizen: 'જવાબદાર નાગરિક',
    violationTypes: 'તમે જે પ્રકારના ઉલ્લંઘનની જાણ કરી શકો છો',
    wrongParking: 'ખોટું પાર્કિંગ',
    noHelmet: 'હેલ્મેટ પહેર્યું નથી',
    signalJump: 'સિગ્નલ જમ્પિંગ',
    overSpeeding: 'વધુ ઝડપ',
    wrongSide: 'ખોટી બાજુએ ડ્રાઇવિંગ',
    damagedRoad: 'નુકસાનગ્રસ્ત રસ્તો',
    otherViolation: 'અન્ય ઉલ્લંઘન',
    highAccidentZones: 'ઉચ્ચ અકસ્માત ઝોન',
    selectLanguage: 'ભાષા પસંદ કરો',
    upiId: 'UPI ID',
    connectUpi: 'પુરસ્કારો માટે UPI કનેક્ટ કરો',
    scratchCard: 'સ્ક્રેચ કાર્ડ પુરસ્કાર',
    discountCoupon: 'ડિસ્કાઉન્ટ કૂપન',
    pendingComplaints: 'મંજૂરી માટે બાકી ફરિયાદો',
    approveComplaint: 'મંજૂર કરો',
    rejectComplaint: 'નકારો',
    numberPlate: 'નંબર પ્લેટ',
    voiceDescription: 'વૉઇસ વર્ણન',
    exampleComplaints: 'ઉદાહરણ ફરિયાદો',
    viewExamples: 'ઉદાહરણો જુઓ',
    yourAvatar: 'તમારું અવતાર',
    editProfile: 'પ્રોફાઇલ સંપાદિત કરો',
    name: 'નામ',
    phoneNumber: 'ફોન નંબર',
    save: 'સાચવો',
    rewardsHistory: 'પુરસ્કાર ઇતિહાસ',
    cashReward: 'રોકડ પુરસ્કાર',
    pointsRequired: 'જરૂર�� પોઇન્ટ્સ',
    claimReward: 'પુરસ્કાર દાવો કરો',
    reportDescription: 'વર્ણન',
    location: 'સ્થાન',
  },
  mr: {
    appName: 'नम्मा सुरक्षा',
    slogan: 'अभिमानी नागरिक व्हा',
    loginAsCitizen: 'नागरिक म्हणून लॉगिन',
    loginAsAuthority: 'अधिकारी म्हणून लॉगिन',
    email: 'ईमेल',
    password: 'पासवर्ड',
    login: 'लॉगिन',
    signup: 'साइन अप',
    dashboard: 'डॅशबोर्ड',
    reportAccident: 'अपघात अहवाल',
    reportViolation: 'उल्लंघन अहवाल',
    myRewards: 'माझी बक्षिसे',
    profile: 'प्रोफाइल',
    logout: 'लॉगआउट',
    streaks: 'स्ट्रीक्स',
    points: 'गुण',
    totalComplaints: 'एकूण तक्रारी',
    pendingApproval: 'मंजुरी प्रलंबित',
    approved: 'मंजूर',
    sosEmergency: 'SOS आणीबाणी',
    callAmbulance: 'रुग्णवाहिका कॉल',
    callPolice: 'पोलीस कॉल',
    nearbyHospital: 'जवळील रुग्णालय शोधा',
    emergencyContacted: 'आणीबाणी सेवांशी संपर्क साधला!',
    trafficViolation: 'वाहतूक उल्लंघन',
    uploadPhoto: 'फोटो अपलोड',
    recordVoice: 'आवाज वर्णन रेकॉर्ड करा',
    startRecording: 'रेकॉर्डिंग सुरू करा',
    stopRecording: 'रेकॉर्डिंग थांबवा',
    submitComplaint: 'तक्रार सबमिट करा',
    complaintSubmitted: 'तक्रार यशस्वीरित्या सबमिट केली!',
    congratulations: 'अभिनंदन!',
    newStreakUnlocked: 'तुम्ही नवीन स्ट्रीक अनलॉक केली!',
    rewardEarned: 'बक्षीस मिळवले!',
    shareOnSocial: 'सोशल मीडियावर शेअर करा',
    responsibleCitizen: 'जबाबदार नागरिक',
    violationTypes: 'तुम्ही अहवाल देऊ शकता अशा उल्लंघनाचे प्रकार',
    wrongParking: 'चुकीचे पार्किंग',
    noHelmet: 'हेल्मेट घातलेले नाही',
    signalJump: 'सिग्नल जंपिंग',
    overSpeeding: 'जास्त वेग',
    wrongSide: 'चुकीच्या बाजूला ड्रायव्हिंग',
    damagedRoad: 'खराब झालेला रस्ता',
    otherViolation: 'इतर उल्लंघन',
    highAccidentZones: 'उच्च अपघात क्षेत्र',
    selectLanguage: 'भाषा निवडा',
    upiId: 'UPI ID',
    connectUpi: 'बक्षिसांसाठी UPI कनेक्ट करा',
    scratchCard: 'स्क्रॅच कार्ड बक्षीस',
    discountCoupon: 'सूट कूपन',
    pendingComplaints: 'मंजुरीसाठी प्रलंबित तक्रारी',
    approveComplaint: 'मंजूर करा',
    rejectComplaint: 'नाकारा',
    numberPlate: 'नंबर प्लेट',
    voiceDescription: 'आवाज वर्णन',
    exampleComplaints: 'उदाहरण तक्रारी',
    viewExamples: 'उदाहरणे पहा',
    yourAvatar: 'तुमचा अवतार',
    editProfile: 'प्रोफाइल संपादित करा',
    name: 'नाव',
    phoneNumber: 'फोन नंबर',
    save: 'सेव्ह करा',
    rewardsHistory: 'बक्षिसांचा इतिहास',
    cashReward: 'रोख बक्षीस',
    pointsRequired: 'आवश्यक गुण',
    claimReward: 'बक्षीस दावा करा',
    reportDescription: 'वर्णन',
    location: 'स्थान',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
